---
apiVersion: v1
kind: Pod
metadata:
  name: roboshop-pod

spec: 
    containers:
    - name: roboshop-web
      image: nginx
      ports:
       - containerPort: 80

    - name: sidecar
      image: almalinux
      command: ["sleep", "100"]