apiVersion: v1
kind: Pod
metadata:
  name: roboshop-pod
  namespace: roboshop
 
spec: 
    containers:
    - name: roboshop-web
      image: nginx
      imagePullPolicy: Always
      ports:
       - containerPort: 80