apiVersion: v1
kind: Pod
metadata:
  name: stress
  
spec: 
    containers:
    - name: stress
      image: mareedu868/stress
      imagePullPolicy: Always
      command: ["sleep", "200"]
      resources:
       requests:
        cpu: "125m"
        memory: "125Mi"
       limits:
        cpu: "250m"
        memory: "256Mi"